export const POPUP__PROCESS = 'TYPE__POPUP_PROCESS'
export const POPUP__REQUEST = 'TYPE__POPUP_REQUEST'
export const POPUP__SUCCESS = 'TYPE__POPUP_SUCCESS'
export const POPUP__FAILURE = 'TYPE__POPUP_FAILURE'
